class ResponseCode:

    SUCCESS = "SUCCESS"

    PRODUCT_CREATED = "PRODUCT_CREATED"

    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    PRODUCT_DELETED = "PRODUCT_DELETED"

    PRODUCT_FETCHED = "PRODUCT_FETCHED"

    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"

    SKU_ALREADY_EXISTS = "SKU_ALREADY_EXISTS"

    VALIDATION_ERROR = "VALIDATION_ERROR"

    INTERNAL_SERVER_ERROR = (
        "INTERNAL_SERVER_ERROR"
    )