class ResponseCode:

    SUCCESS = "SUCCESS"

    PRODUCT_CREATED = "PRODUCT_CREATED"

    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    PRODUCT_DELETED = "PRODUCT_DELETED"

    PRODUCT_FETCHED = "PRODUCT_FETCHED"

    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"

    SKU_ALREADY_EXISTS = "SKU_ALREADY_EXISTS"

    VALIDATION_ERROR = "VALIDATION_ERROR"

    CUSTOMER_CREATED = "CUSTOMER_CREATED"

    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"

    CUSTOMER_DELETED = "CUSTOMER_DELETED"

    CUSTOMER_FETCHED = "CUSTOMER_FETCHED"

    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    ORDER_CREATED = "ORDER_CREATED"

    ORDER_FETCHED = "ORDER_FETCHED"

    ORDER_CANCELLED = "ORDER_CANCELLED"

    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"

    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"

    DASHBOARD_FETCHED = "DASHBOARD_FETCHED"
    
    INTERNAL_SERVER_ERROR = (
        "INTERNAL_SERVER_ERROR"
    )